#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          myservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Flask-webserver
### END INIT INFO
 
# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/ubuntu/math_in_python/webserver/layout2
DIR_MAKE=/home/ubuntu/math_in_python/JendasWork/
DIR_AUTO=/home/ubuntu/math_in_python/git_autodeploy
DAEMON=$DIR/routes.py
DAEMON_NAME=FlaskWebserver
 
# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=ubuntu
 
# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/flask/$DAEMON_NAME.pid
 
. /lib/lsb/init-functions
 
do_start () {
    make -C ${DIR_MAKE}
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    PID=$(cat /var/run/flask/FlaskWebserver.pid)
    kill -- -$(ps -o pgid= $PID | grep -o '[0-9]*')
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10 --signal 9
    log_end_msg $?
}
do_img_reload() {
    make -C ${DIR_MAKE}
    ${DIR_AUTO}/ImgGenerate.sh
}

do_img_copy() {
    ${DIR_AUTO}/ImgCopy.sh
}

do_article_reload() {
    cd ${DIR_AUTO}
    ${DIR_AUTO}/createArticles.sh
    cd -
}

do_clear() {
    make -C ${DIR_MAKE} cleanImg
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
    restart)
        do_article_reload
        do_stop
        do_start
        ;;
    reload|force-reload)
        do_img_reload
        do_article_reload
        do_stop
        do_start
        ;;
    articleReload)
        do_article_reload
        ;;
    imgReload)
        do_img_reload
        do_img_copy
        ;;
    imgCopy)
        do_img_copy
        ;;
    cleanImg)
        do_clear
        ;;
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|imgReload|imgCopy|articleReload|cleanImg|status}"
        exit 1
        ;;
 
esac
exit 0
